### ISSUE TITLE
Design issues to resolve.

### ISSUE THREAD

**Issue by aselcillo** [aselcillo/TheLearningGames#45]
LOGIN VIEW:
- Alerts title show index.html (It should be "Login error" or "Validation error").

TEACHERHOME VIEW:
- The popover show "Show Classroom's shop" but inside that view the title is "Rewards shop".
- Also the popover has titles like "Show Missions" or "Show Rules", and it will be better like "Missions" or 
  "Rules"
- Some buttons have the text in Spanish although the rest of the app is in English (example. in Rewards 
  view, the button says "Añadir recompensa").
- In some forms we are using large texts and it makes the text to deform (example. in the student creation, the field repeat password is deformed).
- Maybe we should make the avatars to look smaller, so the users doesn't have to make a big scroll.
- Maybe we should make possible to show the classroom hashcode in the entire app menus (Teacher part).

**Comment by ghost** [comment]
- https://coderwall.com/p/uer3ow/total-input-type-file-style-control-with-pure-css

**Comment by ghost** [comment]
Made points from 1 to 4.

**Comment by aselcillo** [comment]
Made the last point. Both which remain are closed.
