### ISSUE TITLE
Some curious changes

### ISSUE THREAD

**Issue by ghost** [aselcillo/TheLearningGames#50]
- [x] Check blue bar in keyboard in register STUDENT. (only in IOS devices)
- [x] Put the log out button more accessible, maybe in the popover.
- [x] Make the student hashcode input ignoreCase, so by this way we don't need to check if it's wrong.

- [x] Check modal to send message to disabled button.
- [x] Check all the selects modals for make the "select" button disabled if there is no object selected.
- [x] If student level doesn't have title show another thing.

- [x] Check ionicPopups for alerts in IOS devices they are not showed, and create the mission popup (Error when the date is invalid or less than Date.Now())

**Comment by ghost** [comment]
- For the copy to clipboard function: https://stackoverflow.com/questions/36233134/how-to-create-copy-to-clipboard-button-in-html-javascript

- For ignorecase: https://stackoverflow.com/questions/5757101/change-input-to-upper-case
                            https://www.tutorialspoint.com/java/java_string_equalsignorecase.htm

**Comment by aselcillo** [comment]
Copy to clipboard library:
https://clipboardjs.com/
