### ISSUE TITLE
Invalid characters in email (student creation & sign up)

### ISSUE THREAD

**Issue by aselcillo** [aselcillo/TheLearningGames#71]
If the user tries to use an invalid character in the email like "ñ" or "ç" an alert popup shows up saying "Invalid email".
- If the user is signing up his account the user should know if he is using an invalid character, so it is correct.
- But, if the teacher creates a new student, the email is auto-generated, so it is necessary to change those characters inside the function, then the teacher will see the correct auto-generated email in the student dialog.

**Comment by ghost** [comment]
https://stackoverflow.com/questions/9705194/replace-special-characters-in-a-string-with-underscore

**Comment by ghost** [comment]
http://www.designcise.com/web/tutorial/how-to-replace-all-occurrences-of-a-word-in-a-javascript-string

**Comment by ghost** [comment]
It think you coul make a different replace for specific characters, but as I was seeing you probably are going to need to write a line of code for each
