### ISSUE TITLE
There is a problem with notifications.

### ISSUE THREAD

**Issue by aselcillo** [aselcillo/TheLearningGames#74]
I was giving points to a student, and then I saw the notifications. Then the same notification "The student Ivan Gonzalez has unlocked the level 1 in the achievement: Just a bit more" appears 26 times.
I'm not going to clear those notifications to make an analysis of what is happening. 

It seems that we have to take a look at the worst function in our code...

(Edit)
In the student part is happening the same.
There is a problem with the if sentences. We are saying: "if (points > achievementToCheck.requirements)" so is always entering in this block. Even if the achievement is already unlocked by the student. It is doing it 26 times, because that achievement's required points are 75. So until the points came to the maxScore (100) is always sending notifications.

**Comment by ghost** [comment]
That doesn't make sense it's an if not a loop

**Comment by ghost** [comment]
Check when lose an achievement notification parameter the levelAchievement.
Check commented part in checkAchievement
